<script type="text/javascript">
    Event.observe(window, 'load',  function() {
        if (window.productConfigure) {
            productConfigure.addListType('quote_items', {
	            urlFetch: "<?php echo $this->getUrl('*/sales_order/configureQuoteItems') ?>",
//	            urlConfirm: "<?php //echo $this->getUrl('*/sales_order/updateCustomOptions') ?>//",
	            urlSubmit: "<?php echo $this->getUrl('*/sales_order/loadBlock') ?>"
            });
        }
    });
</script>
